CC = gcc
CFLAGS = -Wall -g \pkg-config --cflags gtk+-3.0LIBS = \pkg-config --libs gtk+-3.0\ -lpthread

SRC_DIR = src
INC_DIR = include
OBJ_DIR = obj

TARGET = client_gtk_v2

SRCS = OBJS = 
INC = -I
all: \ 
\:
\tmkdir -p 
\: \t\ \ -o \ 
\/%.o: \/%.c
\t\ \ \ -c $< -o $@

clean:
\trm -rf \ 
.PHONY: all clean
